config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :reipes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reipe.rb
class Reipe < ApplicationRecord
    belongs_to :user
    attachment :image

    with_options presence: true do
        validates :title
        validates :body
        validates :image
    end
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reipes
  attachment :profile_image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    private
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @recipe = Reipe.new
  end

  def edit
  end
end

app/controllers/reipes_controller.rb
class ReipesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @reipes =Reipe.all
  end

  def show
    @reipe = Reipe.find(params[:id])
  end

  def new
    @reipe = Reipe.new

  end
  def create
    @reipe = Reipe.new(reipe_params)
    @reipe.user_id = current_user.id
    if @reipe.save
      redirect_to reipe_path(@reipe)
    else
      render :new
    end
  end

  def edit
    @reipe = Reipe.find(params[:id])
    if @reipe.user != current_user
      redirect_to reipes_path,alert: '不正なアクセスです。'
    end
  end
  def update
    @reipe = Reipe.find(params[:id])
    @reipe.update(reipe_params)
    redirect_to reipe_path(@reipe)
  end
  def delete
    @reipe = Reipe.find(params[:id])
    @reipe.destroy
    redirect_to reipes_path
  end

  private
  def reipe_params
    params.require(:reipe).permit(:title, :body, :image)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user! 
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path ,alert: '不正なアクセスです。'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(usre_params)
    redirect_to user_path(@user)
  end

  private
  def usre_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reipes_helper.rb
module ReipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="section">
  <article class="media">
    <div class="media-content">
      <div class="content has-text-centered">
        <p>
          <strong class="is-size-1" style="font-family: cursive;">recipegram</strong>
        </p>
      </div>
      <div class="columns is-centered">
        <div class="column is-5">
          <% if user_signed_in? %>
          <% else %>
            <br>
            <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-fullwidth" %>
            <br>
            <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-fullwidth" %>
          <% end %>
        </div>
      </div>
    </div>
  </article>
  <br>
  <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
      </figure>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMySQLSample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>


    <nav class="navbar is-warning">
      <div class="navbar-brand">
        <%= link_to root_path, class: "navbar-item" do %>
          <h1 class="title is-4" style="font-family: cursive;">recipegram</h1>
        <% end %>
      </div>

    <% if user_signed_in? %>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "レシピ一覧", reipes_path, class:"navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "新規投稿", new_reipe_path, class:"navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "レシピグラマー一覧" , users_path, class: "button is-warning is-light" %>
              </p>
              <P class="control">
              <%= link_to "マイページ" , user_path(current_user), class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% else%>
      <div id="navbarExampleTransparentExample" class="navbar-menu">
        <div class="navbar-item">
          <%= link_to "レシピ一覧", reipes_path, class:"navbar-item button is-warning is-light" %>
        </div>
        <div class="navbar-item">
          <%= link_to "レシピグラマー一覧" , users_path, class: "button is-warning is-light" %>
        </div>
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">
              <p class="control">
                <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
              </p>
              <p class="control">
                <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
      </nav>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes#index</h1>
<p>Find me in app/views/recipes/index.html.erb</p>

app/views/recipes/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規レシピ作成
      </h1>
    </div>
  </div>
</section>
<%= form_for @recipe do |f| %>

<%= f.label :title %>
<%= f.text_area :title %>

<%= f.label :body %>
<%= f.text_area :body %>

<%= f.label :image %>
<%= f.attachment_field:image %>

<%= f.submit %>

<%= end %=

app/views/recipes/show.html.erb
<h1>Recipes#show</h1>
<p>Find me in app/views/recipes/show.html.erb</p>

app/views/reipes/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ編集
      </h1>
    </div>
  </div>
</section>

<% if @reipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@reipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @reipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @reipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/reipes/index.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @reipes.each do |reipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to reipe_path(reipe) do %>
                  <%= attachment_image_tag reipe, :image %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-left">
                  <figure class="image is-48x48">
                    <%= attachment_image_tag reipe.user, :profile_image, fallback: "no-image.png", class: "profile_image" %>
                  </figure>
                </div>
                <div class="media-content">
                  <div class="title"><%=link_to reipe.user.username, user_path(reipe.user) %></div>
                </div>
              </div>

              <div class="content">
                <time><%= reipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

app/views/reipes/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規レシピ作成
      </h1>
    </div>
  </div>
</section>

<% if @reipe.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@reipe.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @reipe.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @reipe do |f| %>
          <div class="field">
            <%= f.label :title, "レシピ名", class: "label" %>
            <%= f.text_field :title, class: "input" %>
          </div>

          <div class="field">
            <%= f.label :body, "作り方", class: "label" %>
            <%= f.text_area :body, class: "textarea" %>
          </div>

          <div class="field">
            <%= f.label :image, "写真", class: "label" %>
            <%= f.attachment_field :image, class: "input" %>
          </div>

          <%= f.submit '投稿', class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/reipes/show.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        レシピ詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-7">
                <div class="card">
                    <div class="card-image">
                        <figure class="image is-4by3">
                        <%= attachment_image_tag @reipe, :image %>         </figure>
                     </div>
                     <div class="card-content">
                        <div class="media">
                            <div class="media-content">
                            <p class="title is-4"><%= @reipe.title %></p>
                            </div>
                        </div>
                        <div class="content">
                            <table class="table is-narrow">
                              <tr>
                                <th>レシピ</th>
                              </tr>
                              <tr>
                                <td><%= simple_format @reipe.body %></td>
                              </tr>
                            </table>
                            <% if @reipe.user.id == current_user.id %>
                                <%= link_to "edit", edit_reipe_path(@reipe), class:"button is-success" %>
                            <% end %>
                        </div>
                    </div>
                </div>
            </div>

        <div class="column is-4">
            <article class="panel is-link">
                <p class="panel-heading">
                    By <%= @reipe.user.username %>
                </p>
                <div class="panel-block">
                    <p class="control">
                        <%= @reipe.user.profile %>
                    </p>
                </div>
                <%= link_to user_path(@reipe.user), class: "panel-block" do %>
                <span class="panel-icon">
                  <i class="fas fa-user" aria-hidden="true"></i>
                </span>
                <%= @reipe.user.username %> さんのページへ
              <% end %>
            </article>


        </div>
    </div>
</section>

app/views/users/edit.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                ユーザー編集
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-6">
                <%= form_for @user do |f| %>
                    <div class="field">
                        <%= f.label :username, "ユーザー名", class: "label" %>
                        <%= f.text_field :username, class: "input" %>
                    </div>

                    <div class="field">
                        <%= f.label :email, "メールアドレス", class: "label" %>
                        <%= f.email_field :email, class: "input" %>
                    </div>

                    <div class="field">
                        <%= f.label :profile, "プロフィール", class: "label" %>
                        <%= f.text_area :profile, class: "textarea" %>
                    </div>

                    <div class="field">
                        <%= f.label :profile_image, "プロフィール画像", class: "label" %>
                        <%= f.attachment_field :profile_image, class: "input" %>
                    </div>

                    <%= f.submit "更新", class: "button is-success" %>
                <% end %>
            </div>
        </div>
    </div>
</section>

app/views/users/index.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                レシピグラマー一覧
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-multiline">
            <% @users.each do |user| %>
                <div class="column is-3">
                    <div class="card">
                        <div class="card-content">
                            <div class="card-image">
                                <figure class="image">
                                    <%= link_to user_path(user) do %>
                                        <%= attachment_image_tag user, :profile_image, fallback: "no-image.png" %>
                                    <% end %>
                                </figure>
                            </div>
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    <div class="title"><%= link_to user.username, user_path(user) %></div>
                                </div>
                            </div>
                            <div class="content">
                                投稿数:<%= user.reipes.length %>
                            </div>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</section>

app/views/users/show.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                マイページ
            </h1>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-8">
                <div class="columns is-centered">
                    <div class="column is-4">
                        <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
                            <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png" %>
                        </figure>
                    </div>
                    <div class="column is-8">
                        <table class="table is-fullwidth">
                            <tr>
                                <td class="is-size-4">
                                    <strong><%= @user.username %></strong>
                                </td>
                                <% if @user == current_user %>
                                    <td class="is-size-4">
                                        <%= @user.email %>
                                    </td>
                                    <td>
                                    <%= link_to "編集" , edit_user_path(@user),  class: "button is-primary"%>
                                <% end %>
                            </tr>
                        </table>
                        <table class="table is-fullwidth">
                            <tr>
                                <td>
                                    <%= @user.profile %>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @user.reipes.each do |reipe| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
                <%= link_to reipe_path(reipe) do %>
                  <%= attachment_image_tag reipe, :image, fallback: "no-image.png" %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to reipe_path(reipe), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このレシピを見る
                  <% end %>
                  <% if @user == current_user %>
                    <%= link_to edit_reipe_path(reipe), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このレシピを編集する
                    <% end %>
                    <%= link_to reipe_path(reipe), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このレシピを削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="content">
                <time><%= reipe.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>